### PR TITLE
deduplicate code when language argument passed

### PR DESCRIPTION
**Pull request by ChrisCarini**

### CODE REVIEW

**Comment by ChrisCarini** [comment]
Hi @CallMeGreg ! I've opened a handful of small PRs for this repo, but ultimately, I'm wanting to add a feature to filter by 'top n' - I have the feature coded and tested, but because it depends on **this** PR, I can't open the PR against this repo (but, only my fork); see here: https://github.com/ChrisCarini/repo-language-analysis/pull/1

Once this PR (ie, PR#4) is merged, I'll re-open https://github.com/ChrisCarini/repo-language-analysis/pull/1 against your repo!

Neat CLI BTW! 🎉

**Comment by CallMeGreg** [comment]
> Hi @CallMeGreg ! I've opened a handful of small PRs for this repo, but ultimately, I'm wanting to add a feature to filter by 'top n' - I have the feature coded and tested, but because it depends on **this** PR, I can't open the PR against this repo (but, only my fork); see here: [ChrisCarini#1](https://github.com/ChrisCarini/repo-language-analysis/pull/1)
> 
> Once this PR (ie, PR#4) is merged, I'll re-open [ChrisCarini#1](https://github.com/ChrisCarini/repo-language-analysis/pull/1) against your repo!
> 
> Neat CLI BTW! 🎉

Right on, thanks for all the cleanup @ChrisCarini ✨ Full transparency this was thrown together quickly with plans to shift everything to a GitHub CLI extension. Ideally one simple command instead of a noisy nested command & python script. The new home will be [over here](https://github.com/CallMeGreg/gh-language) and when it's functional, I plan to archive this repo. I'll ping you once I'm able to get around to it, love the idea of "top N" results 😃

**Review by CallMeGreg — APPROVED** [review]

**Comment by ChrisCarini** [comment]
> love the idea of "top N" results 😃

Me too; here ya go; was able to open PR against your repo now -> https://github.com/CallMeGreg/repo-language-analysis/pull/5


> Right on, thanks for all the cleanup @ChrisCarini ✨ 

You're welcome, no problem at all! :)

> Full transparency this was thrown together quickly with plans to shift everything to a GitHub CLI extension. Ideally one simple command instead of a noisy nested command & python script. The new home will be [over here](https://github.com/CallMeGreg/gh-language) and when it's functional, I plan to archive this repo. I'll ping you once I'm able to get around to it, love the idea of "top N" results 😃

Awesome! I love the idea to move this to a GH CLI extension! ❤️ 

I was considering having the python script just grab the necessary information from the API/CLI, but I like the extension route better tbh! I'm much less familiar w/ golang, but I may take a stab at playing with it if time permits (no promises). Do feel free to ping/tag me if you make progress on the extension, I'd love to use it (even if in alpha/beta phase)! 😄

**Comment by CallMeGreg** [comment]
@ChrisCarini thanks again! More on the gh extension vision here: https://github.com/CallMeGreg/gh-language/blob/main/command-design.md

**Comment by CallMeGreg** [comment]
@ChrisCarini I just shipped v1.0.0 of the gh cli extension version, give it a look when you can 😃 would love to hear any feedback you might have, feel free to open an issue: https://github.com/CallMeGreg/gh-language

**Pull request merged**
